apiVersion: v1
kind: Service
metadata:
  name: hash-service
  namespace: devops
  labels:
    app: hash-service
spec:
  selector:
    app: hash-deployment
  ports:
    - name: hash-service
      port: 8080
      targetPort: 8080