apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: length-service
  namespace: devops
  labels:
    release: prom-svc-monitor
spec:
  selector:
    matchLabels:
      app: length-service
  endpoints:
    - port: length-service
      interval: 30s
      path: /metrics