apiVersion: v1
kind: Service
metadata:
  name: length-service
  namespace: devops
  labels:
    app: length-service
spec:
  selector:
    app: length-deployment
  ports:
    - name: length-service
      port: 8081
      targetPort: 8081